### PR TITLE
Models

### PR DESCRIPTION
**Pull request by olamilekan000**
added the model directory

### CODE REVIEW

**Comment by olamilekan000** [comment]
Alright

**Comment by olamilekan000** [comment]
how's the project even suppose to look like?

**Comment by olamilekan000** [comment]
Since there's going to still a model and schema, it can alwyas be changed to suit the change.

**Comment by ooade** [comment]
This is the [Project Goal](https://github.com/FBDevCLagos/react-service-app#projects-goal) for now

**Pull request closed without merging**
